{% set opencensus_version = "0.11.2" %}
{% set version = "0.1.3" %}

package:
  name: opencensus-context
  version: {{ version }}

source:
  url: https://github.com/census-instrumentation/opencensus-python/archive/v{{ opencensus_version }}.tar.gz
  sha256: 3e2ed9735e49ea324d402af576d8504fab6a7f664c8c6f20820e1abf242c138

build:
  number: 0
  script: "cd context/opencensus-context && {PYTHON} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - python
    - wheel
    - pip
  run:
    - python
    - contextvars  # [py==36]

test:
  imports:
    - opencensus.common.runtime_context
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/census-instrumentation/opencensus-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The OpenCensus Runtime Context.
  description: |
    The OpenCensus Runtime Context provides in-process context propagation.
    By default, thread local storage is used for Python 2.7, 3.4 and 3.5;
    contextvars is used for Python >= 3.6, which provides asyncio support.
  doc_url: https://github.com/census-instrumentation/opencensus-python/tree/master/context/opencensus-context/examples
  dev_url: https://github.com/census-instrumentation/opencensus-python/tree/master/context/opencensus-context

extra:
  recipe-maintainers:
    - basnijholt
